### PR TITLE
Fix: Fix Notion connector 429 rate-limit error issue #20 /claim #20

### PR DESCRIPTION
**Pull request by shashank40**
Fixes Notion Rate Limit Issue by adding exponential backoff
/claim #20

### CODE REVIEW

**Comment by shashank40** [comment]
@nickscamara

**Comment by nickscamara** [comment]
Hey @shashank40 thanks for the PR. I just tested and I am still getting rate limited. Below is the error.
Also, doesn't seem like it printed the message you logged (Rate limited, retrying in ${exponentialBackoff} seconds...)

Lmk if you can fix it, thanks!

```@notionhq/client warn: request fail {
  code: 'rate_limited',
  message: 'You have been rate limited. Please try again in a few minutes.'
}
An error occurred: APIResponseError: You have been rate limited. Please try again in a few minutes.
    at buildRequestError (/Users/nicolascamara/Documents/GitHub/scraper-js/node_modules/@notionhq/client/src/errors.ts:240:12)
    at Client.request (/Users/nicolascamara/Documents/GitHub/scraper-js/node_modules/@notionhq/client/src/Client.ts:218:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'rate_limited',
  status: 429,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'x-powered-by': [Array],
      'x-notion-request-id': [Array],
      'retry-after': [Array],
      etag: [Array],
      vary: [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: '{"object":"error","status":429,"code":"rate_limited","message":"You have been rate limited. Please try again in a few minutes.","request_id":"5c58f934-53e9-4104-97be-awdwadaawd"}'
}
APIResponseError: You have been rate limited. Please try again in a few minutes.
    at buildRequestError (/Users/nicolascamara/Documents/GitHub/scraper-js/node_modules/@notionhq/client/src/errors.ts:240:12)
    at Client.request (/Users/nicolascamara/Documents/GitHub/scraper-js/node_modules/@notionhq/client/src/Client.ts:218:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'rate_limited',
  status: 429,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'x-powered-by': [Array],
      'x-notion-request-id': [Array],
      'retry-after': [Array],
      etag: [Array],
      vary: [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: '{"object":"error","status":429,"code":"rate_limited","message":"You have been rate limited. Please try again in a few minutes.","request_id":"5c58f934-53e9-4104-97be-awdwadaawd"}'
}
@notionhq/client warn: request fail {
  code: 'rate_limited',
  message: 'You have been rate limited. Please try again in a few minutes.'
}

```

**Comment by shashank40** [comment]
Hey @nickscamara Can you please point me exactly how to reproduce the steps so that i can understand the flow better?
I don't see a local setup readme for the same.

**Comment by nickscamara** [comment]
Hey @shashank40, I connected a Notion account on Nango.dev. There you get a connection id that you can use to authorize and test the connector. I then ingested a database that I have of around 100 pages.

**Comment by nickscamara** [comment]
@shashank40 any updates here?

**Comment by shashank40** [comment]
Hey @nickscamara , got stuck with my daily job today. 
Most probably by EOD today.
Just a bit of suggestion, the Open-Source local setup readme is something we might need in future for a perfect local setup so tha we can easily replicate issue.
Apart from that, i am on it.

**Comment by nickscamara** [comment]
Sounds good, for sure. @shashank40 it seems like there could be some issue around the recursive step of the implementation.

**Comment by shashank40** [comment]
Added the changes. Can you check now? @nickscamara

**Comment by nickscamara** [comment]
That fixed the error, but yea still not working. (the expo backoof rate limit impl itself works), but I think there could be an issue with the recursive nature of the notion function.  There aren't that many documents in the database I am testing..

**Comment by nickscamara** [comment]
After a while, it seems to fail on the backoff as well, but I think that's not the big issue here and instead the recursive nature of it.
```@notionhq/client warn: request fail {
  code: 'rate_limited',
  message: 'You have been rate limited. Please try again in a few minutes.'
}
Rate limited, retrying in 1 seconds...
An error occurred: TypeError: Cannot read properties of undefined (reading 'has_more')
    at /Users/nicolascamara/Documents/GitHub/scraper-js/node_modules/@mendable/data-connectors/src/providers/Notion/index.ts:79:16
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nicolascamara/Documents/GitHub/scraper-js/node_modules/@mendable/data-connectors/dist/index.js:49:24)
TypeError: Cannot read properties of undefined (reading 'has_more')
    at /Users/nicolascamara/Documents/GitHub/scraper-js/node_modules/@mendable/data-connectors/src/providers/Notion/index.ts:79:16
    at Generator.next (<anonymous>)```

**Comment by nickscamara** [comment]
The above happens because eitherr req or req.has_more is undefined, a simple check there should fix this issue

**Comment by shashank40** [comment]
So what i just realised is that as the 

- Rate-limit error was being reached every single time 
- So we never realised the issue that req being undefined could cause an issue during the loop
- So we never checked that. 

Now i have made 3 modifications in the latest commit
- Handling other type of errors
- req being checked if its undefined or not
- Also making exponentialBackoff variable global as the backoff limit set in recursiveBlockChildren and getDocuments should be respected by each other during the api calls.

@nickscamara

**Comment by abhishek818** [comment]
Shouldnt we use the "retry-after" header field value received in the 429 error response ? Instead of going the expo backoff way. This seems to be more proper since API will only give a response after/at the "retry-after" time and expo backoff way might lead to useless retries or retries for a longer duration.

Pls correct me if it seems wrong.
@nickscamara  @shashank40

**Comment by shashank40** [comment]
It can be done, but in general in 
- rate-limiting cases 
- Or to prevent throttling of servers (of Notion servers)
- Or to prevent DDoS (of Notion servers)

Exponential backoff is the best way to prevent all those at once
@abhishek818

**Comment by abhishek818** [comment]
Did a little research, seems Exponential backoff is the last option.
Refer - 
1. sentry-javascript is well known repo.
[link1](https://github.com/getsentry/sentry-javascript/blob/4b7deee9ca4d2d2b0351dd87f319224868a10107/packages/utils/src/ratelimit.ts#L9)
[link2](https://github.com/getsentry/sentry-javascript/blob/develop/packages/utils/test/ratelimit.test.ts#L74)

2. And a article - Refer "Rate Limiting" section in link3[https://dev.to/brainhubeu/make-notion-search-great-again-notion-api-55pp](url)  (Sentry reference is more reliable)

Also, Notion docs suggest
#Integrations should accommodate variable rate limits by handling HTTP 429 responses and respecting the Retry-After response [header value](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), which is set as an integer number of seconds (in decimal). Requests made after waiting this minimum amount of time should no longer be rate limited.

**Comment by abhishek818** [comment]
Did a little research, seems Exponential backoff is the last option.
Refer - 
1. sentry-javascript is well known repo.
[link1](https://github.com/getsentry/sentry-javascript/blob/4b7deee9ca4d2d2b0351dd87f319224868a10107/packages/utils/src/ratelimit.ts#L9)
[link2](https://github.com/getsentry/sentry-javascript/blob/develop/packages/utils/test/ratelimit.test.ts#L74)

2. And a article - Refer "Rate Limiting" section in [link3](https://dev.to/brainhubeu/make-notion-search-great-again-notion-api-55pp)  (Sentry reference is more reliable)

Also, Notion docs suggest
#Integrations should accommodate variable rate limits by handling HTTP 429 responses and respecting the Retry-After response [header value](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), which is set as an integer number of seconds (in decimal). Requests made after waiting this minimum amount of time should no longer be rate limited.

@shashank40

**Comment by shashank40** [comment]
Yaa, that is an option too and is a very quick and easy change.
 But it totally depends on the use case Mendable wants.
 As explained earlier, exponential backoff serves many more purposes apart from just rate limiting like
 
 - Stops throttling 
 - Stops DDoS attack
 
 If @nickscamara wants, i can extract `'retry-after'` but i it would just serve 1 purpose(and very Notion Specific) and won't be reusable across connectors.
 
 @abhishek818

**Comment by shashank40** [comment]
Hey @nickscamara
Any reviews related to this?

**Comment by nickscamara** [comment]
Hey @shashank40, thanks for those changes but unfortunately it is still not working. The rate limit part works fine but as I mentioned before the problem is in the recursive function and it seems like it is trying to many requests and the rate limit backoff just gets absurd after a while. Fixing the recursive function should fix the issue. Lmk if you wanna do that otherwise I can give you a tip for implementing the rate limit.

**Comment by shashank40** [comment]
Sure @nickscamara , i will have a look at some approaches to 
- Make recursive function a bit more optimal
- Not letting backoff go to absurdly high limits

**Comment by shashank40** [comment]
Hey @nickscamara!
I have been looking at different ways of delay(in which i made a bit of changes after testing) + recursion(no changes were needed ).

As i see [here](https://developers.notion.com/reference/get-block-children#:~:text=In%20order%20to%20receive%20a%20complete%20representation%20of%20a%20block%2C%20you%20may%20need%20to%20recursively%20retrieve%20the%20block%20children%20of%20child%20blocks.). Recursion was the way specified and this approach is working for me fine after i did a local setup with a lot many pages in my notion. (Screenshots attached)

Screenshot 2024-03-06 at 3 45 40 AM
Screenshot 2024-03-06 at 3 46 14 AM


**2 reasons i found out why the failure happens(as this happened with me too)**
- If we turn on auto sync in Nango, this fetches everything repeatedly from Notion and exhausts the API limit(which cannot be altered) and so we struggle with the limit. **Solution**? Turn off auto sync or increase the gap between syncs.
- Fast retries request even during rate_limit is reached.(This has been fixed)


I have tested it and it works fine for me.
Would like to know if it works for you as well?

**Comment by abhishek818** [comment]
Finally you used retry-after, don't forget my tip of $500, 😂.
@shashank40

**Comment by shashank40** [comment]
@abhishek818 😂. Yaaaa, Notion API is quite sadistic.

Even though i skipped it first and wanted to go with exponential, but eventually changed it because of the nature of API.

And was a quick change.

**Comment by shashank40** [comment]
Thanks @nickscamara 
Would love to get into more deeper issues at Mendable to solve.

**Pull request merged**
