### PR TITLE
Feature: Youtube Data Connector

### PR DESCRIPTION
**Pull request by akhilphenom**
Issue #1 
/claim #1

### CODE REVIEW

**Comment by nickscamara** [comment]
Seems like the captions SDK doesn't work. listCaptions doens't exist.

Also, next time please wait until you are assigned otherwise we can't give you the bounty

**Comment by nickscamara** [comment]
Quick note: based on the api it seems like [captions.download](https://developers.google.com/youtube/v3/docs/captions/download) should be used to get the transcript.

**Comment by akhilphenom** [comment]
@nickscamara  Yeah sorry for my confusion. I have updated the PR

**Comment by nickscamara** [comment]
Hi @akhilphenom thanks for the update. Unfortunately there is quite a lot of things wrong:
- For the download to work you need to pass the capition id retrieved by the list.captions
- The YouTube regex fails to grab some videos
- The output of download comes in binary and there is no parsing for that.
- The channel one doesn't seem to be working.

The time spent testing this unfortunately is not worth it. 

So, I am gonna close this for now but I am going to **tip you for your work**. Thanks for attempting, I appreciate. And please next time wait until you are assigned other

**Pull request closed without merging**
